# Generated by Django 5.0.3 on 2024-03-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_cover_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_posted',
            new_name='save_as_draft',
        ),
    ]
